"""update_field_update_at_in_users_table

Revision ID: b251bea84b27
Revises: 7a2035b04cce
Create Date: 2024-06-24 11:59:36.572344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b251bea84b27'
down_revision: Union[str, None] = '7a2035b04cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
